name: ml_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - pandas=2.3.2
  - numpy=2.3.3
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - wandb=0.22.0
  - pydantic=2.11.9
  - gitpython=3.1.45
  - python-dotenv=1.1.1
  - pip
  - pip:
      - lightgbm
      - xgboost
      - torch
